### ISSUE TITLE
MD5 value not identical than in tutorial

### ISSUE THREAD

**Issue by rvplan** [guino/LSCOutdoor1080P#2]
Hello,
Great work.
The LSC Outdoor Cam device I bought was already in firmware v2.10.36
I've been able to follow steps until loading anyka_ipc in ROM patcher website (step 9).
But the MD5 is not the same.
As you ordered: VERIFY that the md5 value displayed matches this(...) if it doesn't: stop!
So I stopped! ;-) But what is the option now?
Does it mean the device is too new? Too old?
Is there a workaround?
Don't want to brick the device (yet)!
Any advice much appreciated.
Best

**Comment by guino** [comment]
@rvplan You can follow [option 3](https://github.com/guino/LSCOutdoor1080P#option-3----if-youre-not-on-21036) to download/extract the 'known' version of 2.10.36 so the md5 should match and you should get it working as expected.

If you like, you can post a zip of your anyka_ipc for me to review -- sometimes the file difference is minor and I could add it to the list of md5s that will work. It is unlikely that I'll make a different patch for the same version (because the changes were extensive).

**Comment by rvplan** [comment]
Hello @guino,
Thx for super rapid and useful answer.
Works like a charm!
